######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 13:56:59 2011
######################################################################

TEMPLATE = app

TARGET = lib_nibbler_Qt.so

DEPENDPATH += .

INCLUDEPATH += .

QMAKE_CFLAGS += -fPIC

QMAKE_CXXFLAGS += -fPIC

QMAKE_LFLAGS += -shared

INCPATH += ./../Core/

# Input

HEADERS += lib.hh \
    nibblerwidget.hh
SOURCES += lib.cpp \
    nibblerwidget.cpp
